base_url: http://localhost:3000
# base_url: http://app.shopvox.com
# base_url: http://app.shopvox-staging.com
# new_account_url: http://app.localhost:3000
# currency: $
# currency_separator: ","
# email_url: https://mail.google.com
